name: 'Run Tests'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    if: |
      contains(github.event.commits[0].message, '[skip ci]') == false &&
      contains(github.event.commits[0].message, '[ci skip]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: 'Checkout Git repository with history for all branches and tags'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install, lint, and test'
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test
